// Questions
var q = [
  'How many users have ever engaged',
  'How many people are in your target market?',
  'How many users do your competitors have?',
  'How much time and money do users in your target market waste before switching to your product/service?',
  'What are some trends in your target market, and related markets?',
  'Why are you uniquely qualified to work on this?',
  'Why do you want to dedicate your life to working on this?',
  'How much money could you make per year?',
  'How does this become a billion-dollar company?',
  'Can’t QA do it themselves?',
  'How much will users pay?',
  'How do you, test the market?',
  'How far can you get by the end of YC?',
  "Why can't they build this in-house?",
  'What’s your sales model / go-to-market?',
  'What would pipeline deals look like? Who would be in the pipeline?',
  'Why go to YC now and not after proving sales model?',
  'Milestones and revenue targets for 3/5/7 years?',
  'Other challenges? What YC help you will need in the next 3-4 months?',
  'Where do new users come from?',
  'Are you open to changing your idea?',
  'What is the next step with the product evolution?',
  'Who might become competitors?',
  'What systems have you hacked?',
  'What are the top things users want?',
  'Tell us something surprising you have done?',
  'What is your distribution strategy?',
  'Will your team stick at this?',
  'How do we know your team will stick together?',
  "What's the biggest mistake you have made?",
  'Who are your competitors?',
  "Why isn't someone already doing this?",
  'Who is going to be your first paying customer?',
  'How big an opportunity is there?',
  'What makes new users try you?',
  'What else have you created together?',
  'What is your growth like?',
  "Six months from now, what's going to be your biggest problem?",
  'What have you learned so far from working on your product?',
  'Why did you pick this idea to work on?',
  "What will you do if we don't fund you?",
  'What resistance will they have to trying you and how will you overcome it?',
  'How long can you go before funding?',
  'Why will you succeed?',
  'How did your team meet?',
  'Where is the rocket science here?',
  'Who in your team does what?',
  "What are the key things about your field that outsiders don't understand?",
  "What's the funniest thing that has happened to you?",
  'What has surprised you about user behaviour?',
  'Who would you hire or how would you add to your team?',
  'How will you make money?',
  'Have you raised funding?',
  "How do you know customers need what you're making?",
  'Who would use your product?',
  'How will customers and/or users find out about you?',
  'If your startup succeeds, what additional areas might you be able to expand into?',
  'How does your product work in more detail?',
  'What competition do you fear most?',
  "Someone just showed us an idea like this right before you guys. I don't like it. What else do you have?",
  'How much does customer acquisition cost?',
  'Will you reincorporate as a US company?',
  'What is your user growth rate?',
  'What part of your project are you going to build first?',
  'Do you have a demo? Could I see it?',
  'How many users are paying?',
  'Why did your team get together?',
  'How are you meeting customers?',
  'In what ways are you resourceful?',
  'Tell us about a tough problem you solved?',
  "Who is 'the boss'?",
  'How much money could you make per year?',
  'What obstacles are you going to face?',
  'Whats something impressive about you as an individual?',
  'How are you going to do B2B sales?',
  'How long have you been working on this?',
  'Have you been working on this part time or full time?',
  'Why have you been part time?',
  'Will you switch to full time if YC funds you? Why?',
  'Why cant other people that are full time founders do this idea?',
  'Whats your plan to get the first 1000 users',
  "What's your exit strategy",
  "Why don't you get a job at a company in the same space?",
  'What would be your core metrics for success?',
  'How you are realistically going to make money?',
  'How excited are you about working on this idea for a significant chunk of your life?',
  'What would be the path to successfully dominating the market',
  'What would be the main challenge behind dominating the market',
  'Why should I believe this will work?',
  'How can you take this idea one step further?',
  'What, exactly, makes you different from existing options?',
  'Why isn’t someone already doing this?',
  'Who needs what you’re making?',
  'How is what you are building different and better than current existing platforms ?',
  'What obstacles are you going to face?',
  'what do other companies not understand that you do?',
  'Whats your go to market strategy?',
  'Who is your target market for this?',
];

// Tips
var tips = [
  'Try to have quick and concise answers.',
  'Try to answer in 2 to 3 sentences.',
  'Answer like you would in a conversation, this is not a presentation.',
  'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
  'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
  'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
  'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).',
];
